name: DynamoRIO Tests
on:
  push:
jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        arch: [arm64, aarch64, x64, x86,]
    steps:  
    - name: Setup and Build DynamoRIO (linux)
      if: runner.os == 'Linux'
      run: | 
        sudo apt-get update
        sudo apt-get install cmake g++ g++-multilib doxygen git zlib1g-dev libunwind-dev libsnappy-dev liblz4-dev
        git clone --recurse-submodules -j4 https://github.com/DynamoRIO/dynamorio.git
    - name: Run tests
      run: |
        set +e
        mkdir -p dynamoriologs
        cd dynamorio && mkdir build && cd build
        cmake -DBUILD_TESTS=ON ..
        make -j6
        make test
        ctest
      continue-on-error: true
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.arch }}
        path: dynamoriologs/dynamorio-test-on-${{ matrix.os }}-under-${{ matrix.arch }}.log
